### ISSUE TITLE
Escape escape

### ISSUE THREAD

**Issue by jtsagata** [adoyle-h/shell-general-colors#1]
Provide and option to escape '\'  Expected  output will clarify this better :

     BLACK='\\e[30m'
     RED='\\e[31m'

**Comment by adoyle-h** [comment]
Why do you need `\\e[31m`? It is not an ANSI escape code.

![image](https://user-images.githubusercontent.com/1998490/76374781-1e62a880-637f-11ea-93d0-50860e687afd.png)
